using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Sunridge.Models
{
    public class Inventory
    {
        #region Inventory-Id (PK)
        // Inventory-Id: The Primary Key of the Inventory Table (autogenerated)
        [Key]
        public int Id { get; set; }
        #endregion
        #region Inventory-ItemName
        //Lot-LotNumber: The Inventory's Item Name
        [Display(Name = "Item Name")]                         // Set the AutoGenerated label to "Item Name"
        public string ItemName { get; set; }
        #endregion

        #region Bridging Table Collections
        public virtual ICollection<Lot_Inventory> Lot_Inventories { get; set; }
        #endregion

        #region Table Diagram
        // EXAMPLE:
        //  __________________________
        // | Id     | Item Name       |
        // |________|_________________|
        // | 1      | Septic System   |
        // |--------|-----------------|
        // | 2      | Solar Panel     |
        // |--------|-----------------|
        // | 3      | Back Flow Valve |
        // |--------|-----------------|
        // | 4      | Propane Tank    |
        // |________|_________________|
        #endregion
    }
}
