using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sunridge.Models
{
    public class LostItem
    {
        #region LostItem-Id (PK)
        // LostItem-Id: The Primary Key of the LostItem Table
        [Key]                                                   // Ensure that the Id is the Primary Key
        public int Id { get; set; }
        #endregion
        #region LostItem-Image
        // The Image of the found LostItem.
        public string Image { get; set; }
        #endregion
        #region LostItem-Status
        //LostItem-Status: The Lost Item's Status as either a Lost item or a Found item.
        [Display(Name = "Status")]                         // Set the AutoGenerated label to "Status"
        public string Status { get; set; }
        #endregion
        #region LostItem-Date
        // LostItem-Date: The Date the LostItem was found
        [Display(Name = "Date")]                                // Set the AutoGenerated label to "Date"
        [DisplayFormat(DataFormatString = "{0:MMM dd, yyyy}")]  // Set the Date Formatting to the standard Month/Day/Year. (Ex: Jan 1, 2021)
        public DateTime Date { get; set; }
        #endregion
        #region LostItem-Name
        //LostItem-Description: The display name made by a User describing the lost item they found.
        [Display(Name = "Name")]                         // Set the AutoGenerated label to "Name"
        public string Name { get; set; }
        #endregion
        #region LostItem-Description
        //LostItem-Description: The written description left by a User describing the lost item they found.
        [Display(Name = "Description")]                         // Set the AutoGenerated label to "Description"
        public string Description { get; set; }
        #endregion
        #region LostItem-ExpirationDate
        //LostItem-ExpirationDate: The Expiration Date for the row (after so many days LostItem's Active field is set to FALSE).
        [Display(Name = "Expiration Date")]                         // Set the AutoGenerated label to "Expiration Date"
        public DateTime ExpirationDate { get; set; }
        #endregion
        #region LostItem-Active
        //LostItem-Active: The Status of Activity for a Lost and Found item.
        [Display(Name = "Active")]                         // Set the AutoGenerated label to "Active"
        [DefaultValue(true)]
        public bool Active { get; set; }
        #endregion
        #region LostItem-DisplayEmail
        //LostItem-DisplayEmail: The Status of the Email Display for a Lost and Found item.
        [Display(Name = "Email Status")]                         // Set the AutoGenerated label to "Email Status"
        public bool DisplayEmail { get; set; }
        #endregion
        #region LostItem-DisplayPhone
        //LostItem-DisplayPhone: The Status of the PHone Display for a Lost and Found item.
        [Display(Name = "Phone Status")]                         // Set the AutoGenerated label to "Phone Status"
        public bool DisplayPhone { get; set; }
        #endregion
        #region LostItem-DisplayAddress
        //LostItem-DisplayAddress: The Status of the Address Display for a Lost and Found item.
        [Display(Name = "Address Status")]                         // Set the AutoGenerated label to "Address Status"
        public bool DisplayAddress { get; set; }
        #endregion

        #region Owner (Foreign Key)
        #region Owner-OwnerId (FK)
        //LostItem-OwnerId: The OwnerId Foreign Key to get info about User who found the item.
        [Display(Name = "Owner Id")]
        public string OwnerId { get; set; }
        #endregion
        #region Owner-Model
        [ForeignKey("OwnerId")]
        public virtual Owner Owner { get; set; }
        #endregion
        #endregion
    }
}
