using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sunridge.Models
{
    public class LotFile
    {
        #region LotFile-Id (PK)
        // Lot-Id: The Primary Key of the LotFile Table (autogenerated)
        [Key]
        public int Id { get; set; }
        #endregion
        #region LotFile-Title
        //Lot-LotNumber: The LotFile's Title
        [Display(Name = "Title")]                         // Set the AutoGenerated label to "Title"
        public string Title { get; set; }
        #endregion
        #region LotFile-Description
        //Lot-LotNumber: The LotFile's Description
        [Display(Name = "Description")]                         // Set the AutoGenerated label to "Description"
        public string Description { get; set; }
        #endregion
        #region LotFile-File
        //Lot-LotNumber: The LotFile's location on server
        [Display(Name = "File")]                         // Set the AutoGenerated label to "File"
        public string File { get; set; }
        #endregion
        #region LotFile-Date
        //Lot-LotNumber: The LotFile's Creation Date
        [Display(Name = "Description")]                         // Set the AutoGenerated label to "Date"
        public DateTime Date { get; set; }
        #endregion
        #region Lot (Foreign Key)
        #region LotFile-LotId (FK)
        // LotFile-LotId: The Primary Key of the Lot Table
        [Display(Name = "Lot Id")]
        public int LotId { get; set; }
        #endregion
        #region Lot Model
        //Lot-Id: The LotId Foreign Key to get info about Lot.
        [ForeignKey("LotId")]
        public virtual Lot Lot { get; set; }
        #endregion
        #endregion

        #region Table Diagram
        // EXAMPLE:
        //  _____________________________________________________________________________________
        // | ID     | Item Name       | Title          | Description      | File       | LotId   |
        // |________|_________________|________________|__________________|____________|_________|
        // | 1      | FileName1       | FileTitle1     | FileDescription1 | URL1       | 1       |
        // |--------|-----------------|----------------|------------------|------------|---------|
        // | 2      | FileName2       | FileTitle2     | FileDescription2 | URL2       | 2       |
        // |--------|-----------------|----------------|------------------|------------|---------|
        // | 3      | FileName3       | FileTitle3     | FileDescription3 | URL3       | 3       |
        // |________|_________________|________________|__________________|____________|_________|
        #endregion
    }
}
